services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb3-container
    ports:
      - "8181:8181"
    volumes:
      - ~/.influxdb3_data:/.data
      - ~/.influxdb3_plugins:/plugins
    command: influxdb3 serve --node-id node0 --object-store file --data-dir /.data --plugin-dir /plugins
