[project]
name = "tech-challenge-four"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.49.0",
    "yfinance>=0.2.66",
]
