[project]
name = "tech-challenge-four"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.2",
    "scikit-learn>=1.7.2",
    "tensorflow>=2.20.0",
    "yfinance>=0.2.66",
]
